# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d6fd2baeaba495f2284634185cf5ff24517dd413092d571c8848d549f7816077bede9496491fd06cf7f731f95e7a8d921c005b04e53730109bb92c4deb32c6

test:
  secret_key_base: 2c7690c8b8de89f79147f83c25cd58ac73fd8b4f8933466ff9931b8a0604beb5cd73e8f64549b48658ce12592b379c42d5334a3c2c3211a471759717ccbb4d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
